version: '2' 

services:
        db: 
                image: prephubwifi/db
                restart: always
                environment:
                        POSTGRES_USER: postgres
                        POSTGRES_PASS: postgres
                        POSTGRES_DBNAME: prephubwifi
                        PGPASSWORD: postgres

        server:
                depends_on:
                        - db
                image: prephubwifi/server
                ports:
                        - "8443:8081"
                restart: always
                environment:
                        PG_HOST: db
                        PG_PASSWORD: postgres

#        flux-land:
#                depends_on:
#                  - server
#                image: prephubwifi/frontend
#                restart: always
#                ports:
#                  - "9000:9000"
